version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm run build
artifacts:
  files:
    - dist/index.html
    - dist/styles.css
    - dist/styles.css.map
    - dist/bundle.js
    # The files in cicd-pipeline are not part of the website. 
    # They are needed for the CodePipeline Deploy step.  
    # All cicd-pipeline files will be excluded in the sync to the S3 Static Website.
    - cicd-pipeline/buildspec-deploy.yml
    - cicd-pipeline/website.cfm.yml
    - cicd-pipeline/website-params.json    
  discard-paths: yes
