version: '2'
services:
  react-node-awscli: 
    build: 
      context: .
      dockerfile: .docker/react.node.awscli.dockerfile
    env_file:
      - .secrets/secrets.env
    volumes: 
      - .:/var/www
    ports:
      - "3000:3000"
    command: npm start


# docker-compose build
# docker-compose run --rm --service-ports react-node-awscli npm run build
# docker-compose run react-node-awscli aws --version

