 AWSTemplateFormatVersion: '2010-09-09'
 Description: 'Continuous Delivery Pipeline'
 Parameters: 
  AppName: 
    Description: 'The name of the application'
    Type: String 
  GitHubUser: 
    Description: 'The user of the GitHub repository, must have access to the GitHubToken'
    Type: String
  GitHubOAuthToken:
    Description: 'The OAuthToken of the GitHub user'
    Type: String
  GitHubRepo:
    Description: 'The GitHub repository'
    Type: String 
  GitHubRepoBranch:
    Description: 'The GitHub repository branch'
    Type: String
#  S3WebsiteBucket:
#    Description: 'Bucket name where website will be hosted',
#    Type: String
 Resources:
    S3ArtifactBucket: 
      Description: 'S3 Bucket for storing build artifacts'
      Type: 'AWS::S3::Bucket'
      Properties: 
        BucketName: !Sub '${AppName}-build-s3-${AWS::Region}'      
        VersioningConfiguration:
          Status: Enabled
    S3ArtifactBucketPolicy:
      DependsOn:
      - S3ArtifactBucket
      Description: Setting Amazon S3 bucket policy for external and AWS CodePipeline access
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref S3ArtifactBucket
        PolicyDocument:
          Version: '2012-10-17'
          Id: SSEAndSSLPolicy
          Statement:
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Action: s3:PutObject
            Resource: !Sub '${S3ArtifactBucket.Arn}/*'
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: aws:kms
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource: !Sub '${S3ArtifactBucket.Arn}/*'
            Condition:
              Bool:
                aws:SecureTransport: 'false'   
    CloudFormationTrustRole:
      Description: Creating service role in IAM for AWS CloudFormation
      Type: AWS::IAM::Role
      Properties:
        RoleName: !Sub '${AppName}-cloudformation-role-iam'
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              Service: [cloudformation.amazonaws.com]
            Action: sts:AssumeRole
        Path: /
    CloudFormationRolePolicy:
      Type: AWS::IAM::Policy
      DependsOn: CloudFormationTrustRole
      Description: Setting IAM policy for the service role for AWS CloudFormation
      Properties:
        PolicyName: CloudFormationRolePolicy
        PolicyDocument:
          Statement:
          - Action: ["s3:GetObject", "s3:GetObjectVersion", "s3:GetBucketVersioning"]
            Resource: "*"
            Effect: Allow
          - Action: ["s3:PutObject"]
            Resource: ["arn:aws:s3:::codepipeline*"]
            Effect: Allow
          - Action: ["lambda:*"]
            Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*"
            Effect: Allow
          - Action: ["apigateway:*"]
            Resource: !Sub "arn:aws:apigateway:${AWS::Region}::*"
            Effect: Allow
          - Action: ["iam:GetRole", "iam:CreateRole", "iam:DeleteRole"]
            Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/${AppName}-*"
            Effect: Allow
          - Action: ["iam:AttachRolePolicy", "iam:DetachRolePolicy"]
            Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/${AppName}-*"
            Effect: Allow
          - Action: ["iam:PassRole"]
            Resource: ["*"]
            Effect: Allow
          - Action: ["cloudformation:CreateChangeSet"]
            Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:aws:transform/Serverless-2016-10-31"
            Effect: Allow
        Roles: [!Ref CloudFormationTrustRole]
    CodePipelineIAMRole:
      Type: 'AWS::IAM::Role'
      Description: 'Creating service role in IAM for AWS CodePipeline'
      Properties:
        AssumeRolePolicyDocument: 
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: 
                - 'codepipeline.amazonaws.com'
              Action:
              - 'sts:AssumeRole'
        Policies:
          # https://docs.aws.amazon.com/codepipeline/latest/userguide/how-to-custom-role.html
          - PolicyName: CodePipelineIAMRolePolicy
            PolicyDocument:
              Statement:
              - Action:
                - s3:GetObject
                - s3:GetObjectVersion
                - s3:GetBucketVersioning
                Resource: "*"
                Effect: Allow
              - Action:
                - s3:PutObject
                Resource:
                - arn:aws:s3:::codepipeline*
                - arn:aws:s3:::elasticbeanstalk*
                Effect: Allow
              - Action:
                - codecommit:CancelUploadArchive
                - codecommit:GetBranch
                - codecommit:GetCommit
                - codecommit:GetUploadArchiveStatus
                - codecommit:UploadArchive
                Resource: "*"
                Effect: Allow
              - Action:
                - codedeploy:CreateDeployment
                - codedeploy:GetApplicationRevision
                - codedeploy:GetDeployment
                - codedeploy:GetDeploymentConfig
                - codedeploy:RegisterApplicationRevision
                Resource: "*"
                Effect: Allow
              - Action:
                - elasticbeanstalk:*
                - ec2:*
                - elasticloadbalancing:*
                - autoscaling:*
                - cloudwatch:*
                - s3:*
                - sns:*
                - cloudformation:*
                - rds:*
                - sqs:*
                - ecs:*
                - iam:PassRole
                Resource: "*"
                Effect: Allow
              - Action:
                - lambda:InvokeFunction
                - lambda:ListFunctions
                Resource: "*"
                Effect: Allow
              - Action:
                - opsworks:CreateDeployment
                - opsworks:DescribeApps
                - opsworks:DescribeCommands
                - opsworks:DescribeDeployments
                - opsworks:DescribeInstances
                - opsworks:DescribeStacks
                - opsworks:UpdateApp
                - opsworks:UpdateStack
                Resource: "*"
                Effect: Allow
              - Action:
                - codebuild:BatchGetBuilds
                - codebuild:StartBuild
                Resource: "*"
                Effect: Allow
              Version: '2012-10-17'
        Path: '/'
        RoleName: !Sub '${AppName}-codepipeline-role-iam'
    CodePipeline:
      Type: 'AWS::CodePipeline::Pipeline'
      Properties: 
        ArtifactStore:
          Location: !Ref S3ArtifactBucket
          Type: S3
        RoleArn: !Sub '${CodePipelineIAMRole.Arn}'
        #https://docs.aws.amazon.com/codepipeline/latest/userguide/integrations-action-type.html#integrations-deploy
        #https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#action-requirements
        Stages:
          - Name: Source
            Actions: 
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
              - Name: !Sub '${AppName}-sourceoutput-codepipeline-${AWS::Region}'
              Configuration:
                Owner: !Ref GitHubUser
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubRepoBranch
                OAuthToken: !Ref GitHubOAuthToken
          - Name: Build
            Actions:
            - Name: Build
              InputArtifacts:
              - Name: !Sub '${AppName}-sourceoutput-codepipeline-${AWS::Region}' 
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
              - Name: !Sub '${AppName}-buildoutput-codepipeline-${AWS::Region}'
              Configuration:
                ProjectName: !Sub '${AppName}-website-codebuild-${AWS::Region}'
              RunOrder: 1
          - Name: Deploy
            Actions:
            - Name: create-changeset
              InputArtifacts:
              - Name: !Sub '${AppName}-sourceoutput-codepipeline-${AWS::Region}'
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              OutputArtifacts: []
              Configuration:
                StackName: !Sub "${AppName}-website-stack-cloudformation-${AWS::Region}"
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !Sub '${CloudFormationTrustRole.Arn}'
                ChangeSetName: pipeline-changeset
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: !Sub "${AppName}-sourceoutput-codepipeline-${AWS::Region}::.aws/website.cfm.yml"
                TemplateConfiguration: !Sub "${AppName}-sourceoutput-codepipeline-${AWS::Region}::.aws/website-params.json"
              RunOrder: 1
            - Name: execute-changeset
              InputArtifacts: []
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              OutputArtifacts: []
              Configuration:
                StackName: !Sub "${AppName}-website-stack-cloudformation-${AWS::Region}"
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: pipeline-changeset
              RunOrder: 2
    CodeBuildIAMRole:
      Type: AWS::IAM::Role
      Description: 'Role for CodeBuild Service'
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service: 
              - codebuild.amazonaws.com
            Action: 
            - sts:AssumeRole
        Path: /
        Policies:
          - PolicyName: CodeBuildIAMRolePolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  Effect: Allow
                  Resource: '*'
                - Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  Effect: Allow
                  Resource: 
                  - arn:aws:s3:::codepipeline-us-east-1-*
                  - !Sub '${S3ArtifactBucket.Arn}/*'
        RoleName: !Sub '${AppName}-codebuild-role-iam-${AWS::Region}'
    CodeBuild:
      Description: 'AWS CodeBuild Project'
      Type: 'AWS::CodeBuild::Project'
      Properties:
        Artifacts: 
          Type: 'CODEPIPELINE'
        Description: 'Build stage of the CodePipeline'
        Environment:
          ComputeType: 'BUILD_GENERAL1_SMALL'
          Image: 'aws/codebuild/nodejs:7.0.0'
          Type: 'LINUX_CONTAINER'
        Name: !Sub '${AppName}-website-codebuild-${AWS::Region}'
        ServiceRole: !Sub '${CodeBuildIAMRole.Arn}'
        Source: 
          Type: 'CODEPIPELINE'
        TimeoutInMinutes: 5
