AWSTemplateFormatVersion: '2010-09-09'
Description: 'Website Stack'
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-s3.html
Parameters: 
  AppName: 
    Description: 'The name of the application'
    Type: String 
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      BucketName: !Sub '${AppName}-website-s3'      
      WebsiteConfiguration:
        IndexDocument: index.html
        #ErrorDocument: error.html
    #DeletionPolicy: Retain
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${S3Bucket.Arn}/*'
      Bucket: !Ref S3Bucket
Outputs:
  WebsiteURL:
    Value: !Sub '${S3Bucket.WebsiteURL}'
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Sub 'https://{S3Bucket.DomainName}'
    Description: Name of S3 bucket to hold website content
